name: flip_up_baseline

obs_down_sample_steps: 10 # 3, 1
action_down_sample_steps: 10 # 3, 1

low_dim_obs_horizon: 2
img_obs_horizon: 1
action_horizon: 16
ignore_proprioception: False


shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  # fields under raw and obs must be consistent with FlipUpDataset.raw_to_obs_action()
  raw: # describes what exists in data
    # camera0_rgb:
    #   shape: [3, 224, 224]
    #   type: rgb
    camera1_rgb:
      shape: [3, 224, 224]
      type: rgb
    camera2_rgb:
      shape: [3, 224, 224]
      type: rgb
    ts_pose_fb:
      shape: [7]
      type: low_dim
    ts_pose_command:
      shape: [7]
      type: low_dim
    wrench:
      shape: [6]
      type: low_dim
  obs:
    # camera0_rgb:
    #   shape: [3, 224, 224]
    #   horizon: ${task.img_obs_horizon} # int
    #   down_sample_steps: ${task.obs_down_sample_steps} # int
    #   type: rgb
    #   ignore_by_policy: False
    camera1_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon} # int
      down_sample_steps: ${task.obs_down_sample_steps} # int
      type: rgb
      ignore_by_policy: False
    camera2_rgb:
      shape: [3, 224, 224]
      horizon: ${task.img_obs_horizon} # int
      down_sample_steps: ${task.obs_down_sample_steps} # int
      type: rgb
      ignore_by_policy: False
    robot0_eef_pos:
      shape: [3]
      horizon: ${task.low_dim_obs_horizon} # int
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}
    robot0_eef_rot_axis_angle: # exists in data
      raw_shape: [3]
      shape: [6]
      horizon: ${task.low_dim_obs_horizon} # int
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      rotation_rep: rotation_6d
      ignore_by_policy: ${task.ignore_proprioception}
    robot0_eef_wrench:
      shape: [6]
      horizon: ${task.low_dim_obs_horizon} # int
      down_sample_steps: ${task.obs_down_sample_steps} # float
      type: low_dim
      ignore_by_policy: ${task.ignore_proprioception}

  action: # computed from robot command
    shape: [9]
    horizon: ${task.action_horizon}
    down_sample_steps: ${task.action_down_sample_steps} # int
    rotation_rep: rotation_6d

task_name: &task_name flipup
dataset_path: /home/yifanhou/data/flip_up_500_filtered

env_runner: # used in workspace for computing metrics
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.flip_up_dataset.FlipUpDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  query_frequency_down_sample_steps: 8
  # cache_dir: null
  action_padding: False
  temporally_independent_normalization: False
  seed: 42
  val_ratio: 0.05
